search_repos
thisisolya/ignite pull request #2
Opened 2021-07-28 08:31 UTC by thisisolya

search feature

2021-07-28 10:36 UTC, paleika commented on src/Issues.js
> +                    </>
You can make a presentational component in that file to make layout more readable
``` js
const TotalComments = (props) => (
    <>
        // header and button
    </>
)


const Issues = ({ issueURL, issueTitle, issueComments }) => {

    const [commentsVisibility, setCommentsVisibility] = useState(false);

    return (
        // ...
                {issueComments.edges.length === 0
                    ? <p className="default-message">There are no comments yet.</p>
                    : <TotalComments count={issueComments.totalCount} commentsVisibility={commentsVisibility} setCommentsVisibility={setCommentsVisibility} />}
        // ...
    )
}
```

2021-07-28 10:36 UTC, paleika commented on src/Issues.js
> +                {commentsVisibility && issueComments.edges.map((comment) => (
move map logic inside `<Comments />`, so it looks better and matches the name

2021-07-28 10:36 UTC, paleika commented on src/Comments.js
> +                        <p className="comment-text">{commentText}</p>
Close the component on the same level of indentation where you've opened it, so you don't confuse props and children
``` js
  <Component
    propA
    propB
  >
    <ChildComponent />
  </Component>
```

2021-07-28 10:36 UTC, paleika commented on src/Comments.js
> +                    <h5><a href={authorURL}>{authorLogin}</a></h5>
make it open in a new tab to not lose current app state

2021-07-29 11:14 UTC, paleika requested changes

2021-07-29 11:14 UTC, paleika commented on src/components/SearchResult.js
>                  <SearchResultItems
same as before: move map inside the Items (cause plural means you'll render a collection, not a single item), and pass `repo.node` to the Item component
there is no need to export SearchResultItem from the separate file if you'll use it in the Search Results only

2021-07-29 11:14 UTC, paleika commented on src/components/SearchResultItems.js
> +const TotalIssues = ({ count, issuesVisibility, setIssuesVisibility }) => (
Seems like `<TotalIssues />` and `<TotalComments />` are exactly the same components, so you can make a shared one and reuse it for both lists

2021-07-29 11:14 UTC, paleika commented on src/components/SearchContext.js
> +            <SetSearchContext.Provider value={setSearchedRepos}>
You can pass anything as a value in the context, there is no need to use two different providers to pass two values

2021-07-30 09:16 UTC, YurySolovyov commented on src/components/CommentItem.js
> +const CommentItem = ({ data }) => {
I know you tried to address Nadya's comment, but you actually made it worse.
1. Data is a poor name for a variable almost always (because all we have is some form of data anyway). If this is a `CommentItem` then it should probably be called `comment`
2.  You can still extract properties from the object to make it more readable after you received `comment` prop
  ```js
  const { author, createdAt, bodyText  } = comment;
  ```

2021-07-30 09:18 UTC, YurySolovyov commented on src/components/Header.js
> +                : null}
you can keep the ternary here, or you can try to extract the condition into an `if` guard, move it up, and see if you like it better.

2021-07-30 09:21 UTC, YurySolovyov commented on src/components/SearchContext.js
> +        <SearchContext.Provider value={{ searchedRepos, setSearchedRepos }}>
using context values like this causes additional re-renders, better to move the value into an `api` object and `memo` it with a dependency on `searchedRepos`

2021-07-30 09:22 UTC, YurySolovyov commented on src/components/SearchResult.js
> +                    <SearchResultItem data={repo.node} key={repo.node.id} />
again, `data` -> `repo`, or even `repository`

2021-07-30 09:26 UTC, paleika commented on src/components/CommentItem.js
> +const CommentItem = ({ data }) => {
you can destructure the object before using it in JSX
``` js
const {
  author: { url, login, avatarUrl },
  createdAt,
  bodyText,
} = props.data;
```

2021-07-30 09:26 UTC, paleika commented on src/components/InfoComponent.js
> +        case "ERROR":
you've got several places to hold the error: an error object from SearchContext or 'Error' value of the ViewerContext
can this be standartized? a single place that will reflect that you got an error or the info is still loading

maybe you don't even need to separate viewer and search contexts, just keep loaded results in the different pieces of value object

2021-07-30 09:26 UTC, paleika commented on src/components/Header.js
> +                : null}
try to get rid of ternary when returning null (and all multiline ternaries at all)
you can check the opposite condition, and code will be more readable
```
if (shouldn't render data) {
  return null;
}

return (
  // jsx
)
```

2021-08-03 08:26 UTC, YurySolovyov commented on src/components/DataBaseContext.js
> +    const searchResult = useMemo(() => searchResultStatus, [searchResultStatus]);
This memo does nothing, since it is always re-computed. What were you trying to achieve?

2021-08-03 08:36 UTC, YurySolovyov commented on src/components/Issues.js
> +                    issues={issue.node}
minor naming weirdness: if the component is called `IssueItem`, it is weird to call prop issue**s** (plural)

2021-08-03 09:06 UTC, paleika commented on src/components/SearchResultItem.js
> +    const { url, name, createdAt, owner: { url: ovnerUrl, login }, description, issues } = repository;
you don't need to destructure all
if you see that `url` is not a clear name, you can leave `owner.url`
or you can leave, renaming is absolutely OK - just fix the typo

2021-08-03 09:06 UTC, paleika commented on src/components/Greeting.js
> +            <h2>Hello, {name || login} !</h2>
There is an odd space before the exclamation mark

2021-08-03 09:30 UTC, merged